# Example PHP Schema file
# Use the following command to regenerate entities:
# bin/schema generate-types src/ app/config/schema.yml

rdfa:
  - https://raw.githubusercontent.com/schemaorg/schemaorg/sdo-gozer/data/schema.rdfa
annotationGenerators:
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\PhpDocAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DoctrineOrmAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ConstraintAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DunglasApiAnnotationGenerator
namespaces:
  entity: AppBundle\Entity
types:
  Thing: ~
  Intangible: ~
  StructuredValue: ~
  ContactPoint: ~
  PostalAddress:
    properties:
      addressCountry:
        range: Text
      addressLocality: ~
  Person:
    properties:
      address:
        range: PostalAddress
      email: ~
  ImageObject:
    properties:
      imageName:
        range: Text
      imageFile:
        range: Text
  MediaObject: ~
  CreativeWork:
    properties:
      dateModified:
        range: DateTime

